import {useEffect,useState} from 'react';
import {contentRequest} from '../data/api';
import {CONTENT_BRANDS,type ContentBrand} from '../data/content';
type EmailSettings={fromName:string;fromEmail:string;audienceName:string;contactIds:string[];unsubscribeUrl:string;footer:string};
const blank:EmailSettings={fromName:'',fromEmail:'',audienceName:'',contactIds:[],unsubscribeUrl:'',footer:''};
export function ContentEmailSetup(){
 const [brand,setBrand]=useState<ContentBrand>('operly'),[value,setValue]=useState<EmailSettings>(blank),[query,setQuery]=useState(''),[contacts,setContacts]=useState<Array<{id:string;name:string;email:string}>>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const c=new AbortController();setBusy(true);setNotice('');setContacts([]);contentRequest<Partial<EmailSettings>>(`/connections/${brand}/email`,'GET',undefined,c.signal).then(s=>setValue({...blank,...Object.fromEntries(Object.keys(blank).filter(k=>k in s).map(k=>[k,s[k as keyof EmailSettings]]))})).catch(e=>{if(!c.signal.aborted)setNotice(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[brand]);
 const search=async()=>{setBusy(true);try{const r=await contentRequest<{contacts:typeof contacts;hasMore:boolean}>(`/connections/${brand}/email/contacts?query=${encodeURIComponent(query)}`);setContacts(r.contacts);setNotice(r.hasMore?'Showing the first 100 matches. Narrow the search to find other recipients.':'Select the contacts for this brand’s email audience.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}};
 return <details className="content-connections"><summary>GoHighLevel email sender & audience</summary><p>Connect the brand’s GHL location and user below first, then choose its sender and explicit recipient list here.</p><label className="content-field">Brand<select disabled={busy} value={brand} onChange={e=>setBrand(e.target.value as ContentBrand)}>{Object.entries(CONTENT_BRANDS).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>{[['fromName','Sender name'],['fromEmail','Sender email'],['audienceName','Audience name'],['unsubscribeUrl','Unsubscribe link'],['footer','Business footer / postal address']].map(([key,label])=><label className="content-field" key={key}>{label}<input disabled={busy} type={key==='fromEmail'?'email':'text'} value={String(value[key as keyof EmailSettings])} onChange={e=>setValue(v=>({...v,[key]:e.target.value}))}/></label>)}<label className="content-field">Find recipients<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="content-button" disabled={busy} onClick={()=>void search()}>Search contacts</button><p>{value.contactIds.length} recipients selected. This saved audience is used for future packages.</p><button className="content-button quiet" disabled={busy} onClick={()=>setValue(v=>({...v,contactIds:[]}))}>Clear selection</button><div className="package-contact-list">{contacts.map(c=><label key={c.id}><input type="checkbox" disabled={busy} checked={value.contactIds.includes(c.id)} onChange={e=>setValue(v=>({...v,contactIds:e.target.checked?[...v.contactIds,c.id]:v.contactIds.filter(id=>id!==c.id)}))}/>{c.name} · {c.email}</label>)}</div>{notice&&<p className="content-notice" role="status">{notice}</p>}<button className="content-button primary" disabled={busy||!value.contactIds.length} onClick={async()=>{setBusy(true);try{await contentRequest(`/connections/${brand}/email`,'PUT',value);setNotice('Email sender and audience saved.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Save email setup</button></details>;
}
