import { useCallback,useRef,useState,useEffect,type ReactNode } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { ArrowLeft,Check,Clock3,LoaderCircle,Plus,Sparkles,X } from 'lucide-react';
import { contentRequest } from '../data/api';
import { CONTENT_BRANDS,CONTENT_CHANNELS,type ContentBrand,type ContentDraft,type ContentIdea,type ContentJob,type ContentStatus } from '../data/content';
import { DraftDesk,Content as LegacyContent } from './Content';
import { ContentDictation } from './ContentDictation';
import { ContentEmailSetup } from './ContentEmailSetup';
import './content.css';
import './content-packages.css';

const formats=['blog','email','social-pack','video'];
const names:Record<string,string>={blog:'Blog',email:'Email','social-pack':'Social posts',video:'Video'};
type Package={id:string;brand:ContentBrand;headline:string;description:string;jobs:(ContentJob&{version:number})[];drafts:ContentDraft[];destinationVersion:string};
type Board={ideas:ContentIdea[];packages:Package[]};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Something went wrong';
function stage(p:Package){if(p.jobs.some(j=>['queued','running'].includes(j.status)))return 'making';if(p.drafts.some(d=>d.publications?.length))return 'scheduled';return 'review';}
export function ContentHome(){
  const cache=useQueryClient();const [brand,setBrand]=useState<ContentBrand|'all'>('all'),[tab,setTab]=useState('ideas'),[selected,setSelected]=useState<string|null>(null),[settings,setSettings]=useState(()=>new URLSearchParams(location.search).has('connections')),[manual,setManual]=useState(false),[brief,setBrief]=useState(''),[manualBrand,setManualBrand]=useState<ContentBrand>('operly'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[angle,setAngle]=useState<Record<string,string>>({}),[editingAngle,setEditingAngle]=useState<string|null>(null);
  const requestId=useRef(crypto.randomUUID());
  const board=useQuery({queryKey:['content','packages',brand],queryFn:({signal})=>contentRequest<Board>(`/packages${brand==='all'?'':`?brand=${brand}`}`,'GET',undefined,signal),refetchInterval:5000,retry:false});
  const status=useQuery({queryKey:['content','status'],queryFn:()=>contentRequest<ContentStatus>('/status'),refetchInterval:30000,retry:false});
  const refresh=useCallback(()=>{void cache.invalidateQueries({queryKey:['content']});},[cache]);
  const choose=async(idea:ContentIdea,decision:'make'|'skip')=>{setBusy(idea.id);setError('');try{await contentRequest(`/ideas/${idea.id}/decision`,'POST',{decision,angle:angle[idea.id]||undefined,engine:'claude'});refresh();if(decision==='make'){setSelected(idea.id);setTab('making');}}catch(e){setError(errorText(e));}finally{setBusy('');}};
  const create=async()=>{setBusy('manual');setError('');try{const result=await contentRequest<{jobs:Array<{idea_id:string}>}>('/generate','POST',{brand:manualBrand,brief,kinds:formats,engine:'claude',requestId:requestId.current});requestId.current=crypto.randomUUID();setManual(false);setBrief('');setBrand('all');setSelected(result.jobs[0].idea_id);setTab('making');refresh();}catch(e){setError(errorText(e));}finally{setBusy('');}};
  const packages=board.data?.packages??[];const current=packages.find(p=>p.id===selected);
  if(settings)return <section className="content-room"><button className="content-button quiet" onClick={()=>setSettings(false)}><ArrowLeft size={16}/> Morning desk</button><ContentEmailSetup/><LegacyContent/></section>;
  if(selected)return current?<PackageDesk key={current.id} item={current} status={status.data} onBack={()=>setSelected(null)} refresh={refresh}/>:<section className="content-room"><button className="content-button" onClick={()=>setSelected(null)}>Back to morning desk</button><p role="status">Opening your package…</p>{board.error&&<p role="alert">{errorText(board.error)}</p>}</section>;
  return <section className="content-room package-home">
    <header className="package-welcome"><div><span className="content-eyebrow">YOUR MORNING DESK</span><h1>Good ideas.<br/><span>Your call.</span></h1><p>Choose the ideas worth making. Your team handles the first drafts.</p></div><div><button className="content-button primary" onClick={()=>setManual(true)}><Plus size={16}/> Add your idea</button><button className="content-button quiet" onClick={()=>setSettings(true)}>Publishing & settings</button></div></header>
    <div className="package-toolbar"><nav className="content-segment" aria-label="Content workflow">{[['ideas','Your ideas'],['making','In production'],['review','Ready to review'],['scheduled','Scheduled & sent']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}<span>{key==='ideas'?board.data?.ideas.length??0:packages.filter(p=>stage(p)===key).length}</span></button>)}</nav><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value as typeof brand)}><option value="all">Both brands</option>{Object.entries(CONTENT_BRANDS).map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label></div>
    {(error||board.error)&&<p role="alert" className="content-notice error">{error||errorText(board.error)} <button onClick={refresh}>Refresh</button></p>}
    {board.isPending?<p role="status">Getting your desk ready…</p>:tab==='ideas'?<>
      <div className="package-section-heading"><p>One “Make it” creates a blog, email, social posts and a MiniMax H3 video.</p><button className="content-button" disabled={!!busy} onClick={async()=>{setBusy('scan');try{for(const b of brand==='all'?['operly','r-link']:[brand])await contentRequest('/scan','POST',{brand:b});setError('Research started. Fresh ideas will appear here.');}catch(e){setError(errorText(e));}finally{setBusy('');}}}>Find fresh ideas</button></div>
      <div className="package-ideas">{board.data?.ideas.map((idea,index)=><article className="package-idea" key={idea.id}><div className="package-idea-meta"><span>{String(index+1).padStart(2,'0')}</span><span>{CONTENT_BRANDS[idea.brand]}</span><span>{idea.score!==null?`${idea.score}/100`: 'Your idea'}</span></div><h2>{idea.headline}</h2><p>{idea.description}</p>{idea.recommended_angle&&<p className="package-angle">{idea.recommended_angle}</p>}<div className="package-sources">{idea.signals.filter(s=>/^https?:\/\//.test(s.url)).map((s,i)=><a href={s.url} key={i} target="_blank" rel="noreferrer">Source {i+1}</a>)}</div>{editingAngle===idea.id&&<div><ContentDictation onText={text=>setAngle(old=>({...old,[idea.id]:text}))}/><label className="content-field">Your angle<textarea value={angle[idea.id]??idea.recommended_angle??''} onChange={e=>setAngle(old=>({...old,[idea.id]:e.target.value}))}/></label></div>}<div className="package-idea-actions"><button className="content-button primary" disabled={!!busy} onClick={()=>void choose(idea,'make')}>{busy===idea.id?<LoaderCircle size={16} className="content-spin"/>:<Check size={16}/>} Make it</button><button className="content-button" disabled={!!busy} onClick={()=>setEditingAngle(editingAngle===idea.id?null:idea.id)}>Change the angle</button><button className="content-button quiet" disabled={!!busy} onClick={()=>void choose(idea,'skip')}><X size={16}/> Skip</button></div></article>)}</div>{!board.data?.ideas.length&&<div className="content-empty"><Sparkles/><h2>You’ve cleared your plate.</h2><p>Research brings the next ideas here. You can also add your own.</p></div>}</>:<div className="package-ideas">{packages.filter(p=>stage(p)===tab).map(p=><button className="package-idea package-card" key={p.id} onClick={()=>setSelected(p.id)}><span className="content-eyebrow">{CONTENT_BRANDS[p.brand]}</span><h2>{p.headline}</h2><div className="package-format-status">{formats.map(kind=>{const j=p.jobs.find(j=>j.kind===kind),d=p.drafts.find(d=>d.kind===kind);return <span key={kind} className={j?.status==='failed'?'error':''}>{names[kind]} · {j?.status==='completed'&&d?(d.publications?.some(v=>['failed','unknown','sending'].includes(v.status))?'Needs attention':d.publications?.length?'Scheduled / sent':'Ready'):kind==='video'&&j?.status==='failed'&&/FAL_API_KEY|disabled|not configured/i.test(j.error??'')?'Connection needed':j?.status??'Not started'}</span>;})}</div><strong>Open package →</strong></button>)}{!packages.some(p=>stage(p)===tab)&&<div className="content-empty"><h2>{tab==='making'?'Nothing in production yet.':tab==='review'?'Your next package will land here.':'Your calendar is clear.'}</h2></div>}</div>}
    {manual&&<ContentDialog label="Add an idea" onClose={()=>{if(!busy)setManual(false);}}><button aria-label="Close" className="content-button quiet" disabled={!!busy} onClick={()=>setManual(false)}><X/></button><h2>What should we make?</h2><label className="content-field">Brand<select value={manualBrand} onChange={e=>setManualBrand(e.target.value as ContentBrand)}>{Object.entries(CONTENT_BRANDS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><ContentDictation disabled={!!busy} onText={setBrief}/><label className="content-field">Idea or brief<textarea rows={5} value={brief} onChange={e=>setBrief(e.target.value)}/></label><p>Blog · Email · Social posts · Text-on-screen video</p>{error&&<p role="alert">{error}</p>}<button className="content-button primary" disabled={!!busy||brief.trim().length<5} onClick={()=>void create()}>Make the package</button></ContentDialog>}
  </section>;
}

function PackageDesk({item,status,onBack,refresh}:{item:Package;status?:ContentStatus;onBack:()=>void;refresh:()=>void}){
  const [format,setFormat]=useState('blog'),[instruction,setInstruction]=useState(''),[scope,setScope]=useState('one'),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[scheduling,setScheduling]=useState<{item:Package;status?:ContentStatus}|null>(null);
  const leave=useRef<(()=>Promise<void>)|null>(null);const register=useCallback((fn:(()=>Promise<void>)|null)=>{leave.current=fn;},[]);
  const go=async(fn:()=>void)=>{try{await leave.current?.();fn();}catch(e){setNotice(errorText(e));}};
  const selectedDraft=item.drafts.find(d=>d.kind===format),job=item.jobs.find(j=>j.kind===format);
  const publicationStatus=useQuery({queryKey:['content','publication',selectedDraft?.id],queryFn:()=>contentRequest<{draft:ContentDraft}>(`/drafts/${selectedDraft!.id}`),enabled:!!selectedDraft?.publications?.length,refetchInterval:30000,retry:false});
  const draft=publicationStatus.data?.draft??selectedDraft;
  const revise=async()=>{setBusy('revise');setNotice('');try{await leave.current?.();const latest=await contentRequest<Board>('/packages');const current=latest.packages.find(p=>p.id===item.id)!;const chosen=current.drafts.filter(d=>(scope==='all'||d.kind===format)&&current.jobs.find(j=>j.kind===d.kind)?.status==='completed'&&!d.package_plan_id&&!d.publications?.length);if(!chosen.length)throw new Error('Wait for a draft to finish first');const completed:string[]=[];for(const d of chosen){if(d.publications?.length)throw new Error(`${names[d.kind]} has already been scheduled; it cannot be revised here.`);setNotice(`Revising ${names[d.kind]}…`);try{await contentRequest(`/drafts/${d.id}/revise`,'POST',{version:d.version,instruction,engine:'claude'});completed.push(names[d.kind]);}catch(e){throw new Error(`${completed.length?`${completed.join(', ')} updated. `:''}${names[d.kind]}: ${errorText(e)}`);}}setInstruction('');setNotice('Changes are ready for review. Video caption changes render as a new version.');refresh();}catch(e){setNotice(errorText(e));refresh();}finally{setBusy('');}};
  return <section className="content-room package-desk"><button className="content-button quiet" disabled={!!busy} onClick={()=>void go(onBack)}><ArrowLeft size={16}/> Morning desk</button><header className="package-welcome"><div><span className="content-eyebrow">{CONTENT_BRANDS[item.brand]} · CONTENT PACKAGE</span><h1>{item.headline}</h1></div><button className="content-button primary" disabled={!!busy||!item.drafts.length} onClick={async()=>{setBusy('schedule');try{await leave.current?.();const [board,freshStatus]=await Promise.all([contentRequest<Board>('/packages'),contentRequest<ContentStatus>('/status')]);const latest=board.packages.find(p=>p.id===item.id);if(!latest)throw new Error('Package no longer available');setScheduling({item:latest,status:freshStatus});}catch(e){setNotice(errorText(e));}finally{setBusy('');}}}><Clock3 size={16}/> Schedule package</button></header>
    <nav className="package-format-tabs" aria-label="Package format">{formats.map(kind=>{const j=item.jobs.find(j=>j.kind===kind);return <button key={kind} disabled={!!busy} aria-pressed={format===kind} onClick={()=>void go(()=>setFormat(kind))}>{names[kind]}<small>{j?.status==='completed'?'Ready':kind==='video'&&j?.status==='failed'&&/FAL_API_KEY|disabled|not configured/i.test(j.error??'')?'Connection needed':j?.status??'Not started'}</small></button>;})}</nav>
    <div className="package-revision"><ContentDictation disabled={!!busy} onText={text=>setInstruction(old=>old?`${old} ${text}`:text)}/><label className="content-field">What should change?<textarea rows={2} placeholder="Make the opening punchier. Remove that claim from every version…" value={instruction} disabled={!!busy} onChange={e=>setInstruction(e.target.value)}/></label><div className="package-idea-actions"><select aria-label="Apply change to" value={scope} disabled={!!busy} onChange={e=>setScope(e.target.value)}><option value="one">This format</option><option value="all">Every finished format</option></select><button className="content-button" disabled={!!busy||instruction.trim().length<3||!draft} onClick={()=>void revise()}>{busy?'Applying changes…':'Apply changes'}</button></div></div>
    {[...new Set(item.drafts.map(d=>d.package_plan_id).filter(Boolean))].map(planId=><div key={planId} className="content-notice"><p>A reviewed scheduling plan is saved. If scheduling was interrupted, continue only its unattempted items. Existing attempts will never be resent. To change times or destinations, unlock formats with no publication attempts.</p><ul>{item.drafts.filter(d=>d.package_plan_id===planId).map(d=><li key={d.id}>{names[d.kind]} · {d.publish_scheduled_at?new Date(d.publish_scheduled_at).toLocaleString():'Saved time'} · {(d.publish_channels??d.channels).join(', ')}</li>)}</ul>{(['resume','release'] as const).map(action=><button className="content-button" disabled={!!busy} key={action} onClick={async()=>{setBusy(action);try{const result=await contentRequest<{released?:number;complete?:boolean;results?:Array<{kind:string;error?:string;publications?:Array<{status:string}>}>}>(`/packages/${item.id}/${action}`,'POST',{planId});setNotice(action==='release'?`${result.released} unattempted format(s) unlocked for review.`:result.complete?'Your package is scheduled.':result.results?.map(r=>`${names[r.kind]}: ${r.error??r.publications?.map(p=>p.status).join(', ')}`).join('\n')??'Check publication status.');refresh();}catch(e){setNotice(errorText(e));}finally{setBusy('');}}}>{action==='resume'?'Continue saved schedule':'Unlock unattempted formats'}</button>)}</div>)}
    {notice&&<p className="content-notice" role="status">{notice}</p>}
    {job&&['failed','queued','running','cancelled'].includes(job.status)&&<div className="content-notice"><strong>{names[format]} · {format==='video'&&job.status==='failed'&&/FAL_API_KEY|disabled|not configured/i.test(job.error??'')?'Connection needed':job.status}</strong><p>{job.error||(job.status==='running'?`${Math.round(job.progress)}% · ${job.phase}`:'Waiting for the content engine')}</p>{job.status==='failed'&&<button className="content-button" disabled={!!busy} onClick={async()=>{setBusy('retry');try{await contentRequest(`/jobs/${job.id}/retry`,'POST',{});refresh();}catch(e){setNotice(errorText(e));}finally{setBusy('');}}}>Retry this format</button>}{format==='video'&&job.status==='failed'&&<a href="/setup#media">Check video setup</a>}</div>}
    {draft?.kind==='email'&&draft.publications?.length&&draft.publications.every(p=>p.status==='failed'&&!p.provider_id)?<div className="content-notice"><p>GHL rejected this email before creating a campaign. Fix the sender or audience in Publishing &amp; settings, then make an editable copy. The rejected attempt stays in the history.</p><button className="content-button" disabled={!!busy} onClick={async()=>{setBusy('recover');try{await contentRequest(`/drafts/${draft.id}/recover`,'POST',{version:draft.version,requestId:crypto.randomUUID()});refresh();}catch(e){setNotice(errorText(e));}finally{setBusy('');}}}>Create editable email copy</button></div>:null}
    {draft&&job?.status!=='running'&&job?.status!=='queued'?<DraftDesk key={draft.id} initial={draft} status={status} onBack={onBack} onSaved={refresh} packageMode registerLeave={register}/>:!job?<p>This format has not been started.</p>:null}
    {scheduling&&<PackageSchedule item={scheduling.item} status={scheduling.status} onClose={()=>setScheduling(null)} refresh={refresh}/>}
  </section>;
}

function PackageSchedule({item,status,onClose,refresh}:{item:Package;status?:ContentStatus;onClose:()=>void;refresh:()=>void}){
  const eligible=item.drafts.filter(d=>!d.package_plan_id&&!d.publications?.length&&item.jobs.find(j=>j.kind===d.kind)?.status==='completed');
  const [chosen,setChosen]=useState(()=>eligible.map(d=>d.id));const [times,setTimes]=useState<Record<string,string>>(()=>Object.fromEntries(eligible.map((d,i)=>{const date=new Date();date.setDate(date.getDate()+1);date.setHours(9+i,0,0,0);return [d.id,new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)];})));
  const [channels,setChannels]=useState<Record<string,string[]>>(()=>Object.fromEntries(eligible.map(d=>[d.id,d.kind==='video'?['instagram']:d.channels])));
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[locked,setLocked]=useState(false);const request=useRef(crypto.randomUUID());
  const save=async()=>{setBusy(true);setMessage('');try{const result=await contentRequest<{complete:boolean;results:Array<{kind:string;error?:string;publications?:Array<{channel:string;status:string;detail?:string}>}>}>(`/packages/${item.id}/schedule`,'POST',{requestId:request.current,destinationVersion:item.destinationVersion,entries:eligible.filter(d=>chosen.includes(d.id)).map(d=>({draftId:d.id,version:d.version,channels:channels[d.id],scheduledAt:new Date(times[d.id]).toISOString()}))});setLocked(true);setMessage(result.complete?'Your package is scheduled.':result.results.map(r=>`${names[r.kind]}: ${r.error??r.publications?.map(p=>`${p.channel}: ${p.status}${p.detail?` (${p.detail})`:''}`).join(', ')}`).join('\n'));refresh();}catch(e){setMessage(errorText(e));const status=(e as {status?:number}).status;if(!status||status>=500)setLocked(true);}finally{setBusy(false);}};
  return <ContentDialog label="Schedule package" onClose={()=>{if(!busy)onClose();}}><button className="content-button quiet" aria-label="Close" disabled={busy} onClick={onClose}><X/></button><h2>Ready to go out.</h2><p>Review these versions and their destinations. Scheduling approves and queues the selected formats.</p><p className="content-hint">Times shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}.</p>{eligible.map(d=><fieldset key={d.id}><legend><label><input type="checkbox" disabled={busy||locked} checked={chosen.includes(d.id)} onChange={e=>setChosen(old=>e.target.checked?[...old,d.id]:old.filter(id=>id!==d.id))}/> {names[d.kind]}</label></legend><input aria-label={`${names[d.kind]} schedule time`} disabled={busy||locked} type="datetime-local" value={times[d.id]} onChange={e=>setTimes(old=>({...old,[d.id]:e.target.value}))}/><div>{(d.kind==='video'?['instagram','facebook','linkedin','x']:d.channels).map(channel=>{const c=status?.brands.find(b=>b.brand===item.brand)?.channels.find(c=>c.channel===channel);return <label key={channel}><input type="checkbox" disabled={busy||locked} checked={channels[d.id].includes(channel)} onChange={e=>setChannels(old=>({...old,[d.id]:e.target.checked?[...old[d.id],channel]:old[d.id].filter(c=>c!==channel)}))}/>{CONTENT_CHANNELS[channel as keyof typeof CONTENT_CHANNELS]??channel} <small>{c?.status==='connected'?c.detail:'Connection needed'}</small></label>;})}</div></fieldset>)}{eligible.length<4&&<p className="content-notice">{4-eligible.length} format(s) still in production, already scheduled, or need attention. Only the selected finished versions will be scheduled.</p>}{message&&<p className="content-notice package-result" role="status">{message}</p>}<button className="content-button primary" disabled={busy||locked||!chosen.length||chosen.some(id=>!times[id]||!channels[id]?.length)} onClick={()=>void save()}>{busy?'Scheduling…':'Schedule selected package'}</button></ContentDialog>;
}

function ContentDialog({label,onClose,children}:{label:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="package-modal" aria-label={label} onCancel={e=>{e.preventDefault();onClose();}}>{children}</dialog>;}
